version: '3.7'

services:
  nest:
    container_name: 'nest'
    build:
      context: .
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - nest

  mongo:
    image: bitnami/mongodb:6.0.2
    container_name: 'nest_mongo'
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGODB_ROOT_PASSWORD=rootPass123
      - MONGODB_USERNAME=nest
      - MONGODB_PASSWORD=password
      - MONGODB_DATABASE=nest
    ports:
      - 27017:27017
    networks:
      - nest
networks:
  nest:
volumes:
  mongodb_data: